sonar.projectName=Finisus Web
sonar.sourceEncoding=UTF-8

sonar.sources=src
sonar.tests=src,e2e,integracao-e2e
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=**/*.spec.ts,src/app/infraestrutura/api/backend.dtos.ts
sonar.javascript.lcov.reportPaths=coverage/finisus/lcov.info
sonar.typescript.tsconfigPaths=tsconfig.app.json,tsconfig.spec.json

sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300
